---

- hosts: monitorio

  tasks:
  - import_tasks: tasks/common.yml

  - name: Build images
    environment: "{{ docker_compose }}"
    command: >
      docker-compose
      --file "{{ local_root_dir_path }}/base.yml"
      --file "{{ local_root_dir_path }}/build.yml"
      --file "{{ local_root_dir_path }}/config.yml"
      --file "{{ local_root_dir_path }}/local.yml"
      build

  - name: Re/start stack
    environment: "{{ docker_compose }}"
    command: >
      docker-compose
      --file "{{ local_root_dir_path }}/base.yml"
      --file "{{ local_root_dir_path }}/build.yml"
      --file "{{ local_root_dir_path }}/config.yml"
      --file "{{ local_root_dir_path }}/local.yml"
      up
      --detach
      --force-recreate
