---

- hosts: monitorio

  tasks:
  - name: "Create {{ commit_sha_dir_path }}/"
    file:
      path: "{{ commit_sha_dir_path }}"
      recurse: yes
      state: directory

  - import_tasks: tasks/common.yml

  - name: "Copy docker-compose files to {{ commit_sha_dir_path }}/"
    copy:
      src: "{{ item }}"
      dest: "{{ commit_sha_dir_path }}"
    loop:
    - "{{ local_root_dir_path }}/base.yml"
    - "{{ local_root_dir_path }}/config.yml"
    - "{{ local_root_dir_path }}/production.yml"
    - "{{ local_root_dir_path }}/config.production.yml"
    - "{{ local_root_dir_path }}/networks.production.yml"

  - name: "Pull {{ commit_sha }} images from {{ registry_url }}"
    environment: "{{ docker_compose }}"
    block:
    - name: "Login to {{ registry_url }}"
      command: >
        docker login
          --username "{{ registry_username }}"
          --password "{{ registry_password }}"
          "{{ registry_url }}"
    - name: "Pull {{ commit_sha }} images"
      command: >
        docker-compose
          --file "{{ commit_sha_dir_path }}/base.yml"
          --file "{{ commit_sha_dir_path }}/config.yml"
          --file "{{ commit_sha_dir_path }}/production.yml"
          --file "{{ commit_sha_dir_path }}/config.production.yml"
          --file "{{ commit_sha_dir_path }}/networks.production.yml"
          pull
    - name: "Logout of {{ registry_url }}"
      command: docker logout "{{ registry_url }}"

  - name: Re/start stack
    environment: "{{ docker_compose }}"
    command: >
      docker-compose
        --project-name "{{ project_name }}"
        --file "{{ commit_sha_dir_path }}/base.yml"
        --file "{{ commit_sha_dir_path }}/config.yml"
        --file "{{ commit_sha_dir_path }}/production.yml"
        --file "{{ commit_sha_dir_path }}/config.production.yml"
        --file "{{ commit_sha_dir_path }}/networks.production.yml"
        up
        --detach
        --force-recreate
