---

- name: "Initialize configuration at {{ config_dir_path }}"
  block:
  - name: "Create {{ config_dir_path }} with subdirectories from {{ template_config_dir_path }}"
    file:
      path: "{{ config_dir_path }}/{{ item.path }}"
      state: directory
    with_filetree: "{{ template_config_dir_path }}"
    when: item.state == "directory"

  - name: "Copy configs from {{ template_config_dir_path }} recursively"
    template:
      src: "{{ item.src }}"
      dest: "{{ config_dir_path }}/{{ item.path }}"
    with_filetree: "{{ template_config_dir_path }}"
    when: item.state == "file"

  - name: "Copy the remaining configs from {{ files_config_dir_path }} recursively"
    copy:
      src: "{{ item.src }}"
      dest: "{{ config_dir_path }}/{{ item.path }}"
    with_filetree: "{{ files_config_dir_path }}"
    when: item.state == "file"
