---

# Dangerous settings are explicitly set to False for added security.
sudoers_rewrite_default_sudoers_file: False
sudoers_remove_unauthorized_included_files: False

_sudoer: "{{ non_root_user }}"
user_specifications:
- name: "{{ _sudoer }}"
  users: "{{ _sudoer }}"
  hosts: ALL
  operators: ALL
  commands: ALL
  tags: NOPASSWD

docker_edition: ce
docker_primary_version: 19.03.12
docker_version: "{{ docker_primary_version }}~3-0~ubuntu-bionic"
docker_package: "docker-{{ docker_edition }}={{ docker_version }}"
docker_users:
  - "{{ non_root_user }}"
docker_compose_version: 1.26.2
