galaxy_info:
  role_name: "sudoers"
  author:
    - Tyler Cross
    - Andrew J. Huffman
  company: "Red Hat"
  description: Controls the configuration of the sudoers file and /etc/sudoers.d/ files
  issue_tracker_url: https://github.com/wtcross/ansible-sudoers/issues
  license: MIT
  min_ansible_version: 2.3
  #github_branch: master
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: SLES
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - sudo
    - sudoers
    - admin
    - system

dependencies: []
